package output

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/lichi/fuji/internal/models"
)

// WriteMarkdown outputs analysis results as a Markdown report
func WriteMarkdown(result *models.AnalysisResult) error {
	return WriteMarkdownToWriter(os.Stdout, result)
}

// WriteMarkdownToString returns the report as a string
func WriteMarkdownToString(result *models.AnalysisResult) (string, error) {
	var buf bytes.Buffer
	if err := WriteMarkdownToWriter(&buf, result); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func WriteMarkdownToWriter(w io.Writer, result *models.AnalysisResult) error {
	fmt.Fprintf(w, "# 🗻 Fuji Analysis Report\n\n")
	fmt.Fprintf(w, "**Directory:** `%s`\n\n", result.RootDir)

	// Summary
	fmt.Fprintf(w, "## Summary\n\n")
	fmt.Fprintf(w, "| Metric | Value |\n")
	fmt.Fprintf(w, "|--------|-------|\n")
	fmt.Fprintf(w, "| Files Analyzed | %d |\n", result.Summary.FilesAnalyzed)
	fmt.Fprintf(w, "| Files Flagged | %d |\n", result.Summary.FilesFlagged)
	fmt.Fprintf(w, "| Average Complexity | %.1f |\n", result.Summary.AvgComplexity)
	fmt.Fprintf(w, "| Total Issues | %d |\n", result.Summary.TotalIssues)
	fmt.Fprintf(w, "| AI-Suspected Files | %d |\n", result.Summary.AISuspected)
	fmt.Fprintf(w, "| Security Issues | %d |\n\n", result.Summary.SecurityIssues)

	// Group issues by severity
	var critical, errors, warnings, infos []*fileIssue

	for _, f := range result.Files {
		if len(f.Issues) == 0 {
			continue
		}
		relPath, _ := filepath.Rel(result.RootDir, f.Path)
		for _, issue := range f.Issues {
			fi := &fileIssue{path: relPath, issue: issue}
			switch issue.Severity {
			case models.SeverityCritical:
				critical = append(critical, fi)
			case models.SeverityError:
				errors = append(errors, fi)
			case models.SeverityWarning:
				warnings = append(warnings, fi)
			default:
				infos = append(infos, fi)
			}
		}
	}

	if len(critical) > 0 {
		fmt.Fprintf(w, "## 🔴 Critical Issues\n\n")
		writeIssueTable(w, critical)
	}

	if len(errors) > 0 {
		fmt.Fprintf(w, "## 🟠 Errors\n\n")
		writeIssueTable(w, errors)
	}

	if len(warnings) > 0 {
		fmt.Fprintf(w, "## 🟡 Warnings\n\n")
		writeIssueTable(w, warnings)
	}

	if len(infos) > 0 {
		fmt.Fprintf(w, "## 🔵 Info\n\n")
		writeIssueTable(w, infos)
	}

	// AI-suspected files
	var aiFiles []*models.FileResult
	for _, f := range result.Files {
		if f.AIScore > 50 {
			aiFiles = append(aiFiles, f)
		}
	}

	if len(aiFiles) > 0 {
		fmt.Fprintf(w, "## 🤖 AI-Suspected Files\n\n")
		fmt.Fprintf(w, "| File | AI Probability | Complexity |\n")
		fmt.Fprintf(w, "|------|---------------|------------|\n")
		for _, f := range aiFiles {
			relPath, _ := filepath.Rel(result.RootDir, f.Path)
			bar := makeBar(f.AIScore/100, 10)
			fmt.Fprintf(w, "| `%s` | %s %.0f%% | %d |\n", relPath, bar, f.AIScore, f.Complexity)
		}
		fmt.Fprintf(w, "\n")
	}

	// Footer
	fmt.Fprintf(w, "---\n\n")
	fmt.Fprintf(w, "*Generated by [fuji](https://github.com/lichi/fuji) 🗻*\n")

	return nil
}

type fileIssue struct {
	path  string
	issue models.Issue
}

func writeIssueTable(w io.Writer, issues []*fileIssue) {
	fmt.Fprintf(w, "| File | Line | Type | Message |\n")
	fmt.Fprintf(w, "|------|------|------|---------|\n")
	for _, fi := range issues {
		fmt.Fprintf(w, "| `%s` | %d | %s | %s |\n",
			fi.path, fi.issue.Line, fi.issue.Type, fi.issue.Message)
	}
	fmt.Fprintf(w, "\n")
}

func makeBar(ratio float64, width int) string {
	filled := int(ratio * float64(width))
	if filled > width {
		filled = width
	}
	return strings.Repeat("█", filled) + strings.Repeat("░", width-filled)
}
